### ISSUE TITLE
MFT plugin arguments

### ISSUE THREAD

**Issue by Zawadidone** [fox-it/dissect.target#130]
From [PR](https://github.com/fox-it/flow.record/issues/40#issuecomment-1380306454)
> I agree, so a flag should only be used to deviate from the default, and the default should be changed to something sane.
> I think splitting it up like that is perhaps a bit too much, not to mention that it would complicate the mft plugin quite a bit. I think in general you'd want all timestamps, so I believe that should be the default. So perhaps something like:

```
target-query -f mft  # individual records for every timestamp
target-query -f mft --grouped  # or --mft-grouped, to group the timestamps into one record
target-query -f mft --std-only  #  or --mft-std-only, standard information records only
```

**Comment by Zawadidone** [comment]
I can work on this after 4/5 weeks.

**Comment by Zawadidone** [comment]
Based on the feature added in #142 and the enhancements made in flow.record [https://github.com/fox-it/flow.record/pull/51](https://github.com/fox-it/flow.record/pull/51), [https://github.com/fox-it/flow.record/pull/47](https://github.com/fox-it/flow.record/pull/47) this issue can be closed right? From my perspective the arguments `std-only` or `filename-only` are not needed.

**Comment by Schamper** [comment]
Agreed!
