### ISSUE TITLE
TarLoader issues

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/dissect.target#135]
We've come across two issues regarding the use of tar-files:

1. With the merge of #112, the class `TarFile` is removed. This however [breaks the AsdfLoader](https://github.com/fox-it/dissect.target/blob/main/dissect/target/loaders/asdf.py#L5).
2. In the TarLoader, [directories are skipped](https://github.com/fox-it/dissect.target/blob/main/dissect/target/loaders/tar.py#L37). It seems that as result of this, empty folders are not included in for example `target.walkfs()`, although they might be of value from a forensic point of view. The [current test](https://github.com/fox-it/dissect.target/blob/main/tests/test_loaders_tar.py) does not include the occurrence of empty folders within a tar-file.

**Comment by Schamper** [comment]
I believe both of these issues are currently resolved. Can you confirm and close the issue if this is the case?

**Comment by JSCU-CNI** [comment]
The latter issue has indeed been fixed with #144 and #195. The first issue however still seems to be present. The `AsdfLoader` still tries to import `TarFile` from `dissect.target.loaders.tar` in [`loaders/asdf.py`](https://github.com/fox-it/dissect.target/blob/main/dissect/target/loaders/asdf.py#L6).
