### ISSUE TITLE
Windows plugins datetime fields

### ISSUE THREAD

**Issue by Zawadidone** [fox-it/dissect.target#147]
The `*_date` fields use the type `string`.

https://github.com/fox-it/dissect.target/blob/7a2e0dca7b1fa0de1bb68d4ee8b04424367e7155/dissect/target/plugins/os/windows/regf/usb.py#L22-L25

But the docstring states that these fields use the type `datetime`.

https://github.com/fox-it/dissect.target/blob/7a2e0dca7b1fa0de1bb68d4ee8b04424367e7155/dissect/target/plugins/os/windows/regf/usb.py#L105-L108

Is this intended or should the type of these fields be adjusted to `datetime`?

The same applies for https://github.com/fox-it/dissect.target/blob/7a2e0dca7b1fa0de1bb68d4ee8b04424367e7155/dissect/target/plugins/os/windows/tasks.py#L19

**Comment by Schamper** [comment]
At least the USB ones look like a bug. There's also a type with `instal` it looks like. Feel free to fix in a PR.

As for the task one, looks like that comes from the `RegistrationInfo/Date` field in the task XML. I don't know the purpose of this field by heart, but if it's indeed a timestamp then it makes sense to also start parsing that as a `datetime`.

**Comment by Zawadidone** [comment]
Microsoft states that it is a date element.

> When reading or writing XML for a task, the registration date is specified using the Date element of the Task Scheduler schema. - https://learn.microsoft.com/en-us/windows/win32/taskschd/registrationinfo-date, https://learn.microsoft.com/en-us/windows/win32/taskschd/taskschedulerschema-date-registrationinfotype-element

**Comment by Zawadidone** [comment]
Closed in #187
