### ISSUE TITLE
Amcache namespace

### ISSUE THREAD

**Issue by Zawadidone** [fox-it/dissect.target#149]
Is it intended that the function names `files` and `programs` don't start with `amcache.`?

```bash
target-query -l | grep amcache
        amcache:
          amcache.applaunches - Return AppLaunchAppcompatRecord records from Amcache applaunch files (Windows 11 22H2 or later). (output: records)
          amcache.application_files - Return InventoryApplicationFile records from Amcache hive. (output: records)
          amcache.applications - Return InventoryApplication records from Amcache hive. (output: records)
          amcache.device_containers - Return InventoryDeviceContainer records from Amcache hive. (output: records)
          amcache.drivers - Return InventoryDriverBinary records from Amcache hive. (output: records)
          amcache.shortcuts - Return InventoryApplicationShortcut records from Amcache hive. (output: records)
          files - Return File records from Amcache hive. (output: records)
          programs - Return Programs records from Amcache hive. (output: records)
```

**Comment by Schamper** [comment]
Nope, looks like a bug. Probably because it's implemented in a mixin.

@cecinestpasunepipe I believe this will also break with your current proposal for how to call namespaced functions.

**Comment by cecinestpasunepipe** [comment]
> Nope, looks like a bug. Probably because it's implemented in a mixin.
> 
> @cecinestpasunepipe I believe this will also break with your current proposal for how to call namespaced functions.

Interesting, at least to some degree the current proposal seems to work fine with this, although it would be better if it was properly namespaced..
