### ISSUE TITLE
Filesystems incorrectly escape backslashes in files and folders

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/dissect.target#201]
Some filesystems seem to incorrectly escape backslashes in files and folders. This is likely unnecessary since https://github.com/fox-it/dissect.target/commit/763fddca476d604ad601fd2bce516e1aa89b04a0 introduced the `alt_separator` behaviour.

Given the `/example` folder below, plugins like walkfs and tools like target-shell will break when encountering a filesystem entry with a backslash.

```
$ tree /example
/example
├── backslash\folder
│   └── file.txt
└── back\slash.txt
```

```
# example on ext4 filesystem
$ target-query -f walkfs example.vmdk
...
dissect.target.exceptions.FileNotFoundError: /example/backslash\folder
```

At least four filesystem implementations use this form of escaping:
- dissect.ntfs (https://github.com/fox-it/dissect.ntfs/blob/main/dissect/ntfs/mft.py#L76)
- dissect.xfs (https://github.com/fox-it/dissect.xfs/blob/main/dissect/xfs/xfs.py#L58)
- dissect.extfs (https://github.com/fox-it/dissect.extfs/blob/main/dissect/extfs/extfs.py#L113)
- dissect.fat (https://github.com/fox-it/dissect.fat/blob/main/dissect/fat/fat.py#L94)
- and perhaps others (https://github.com/search?q=org%3Afox-it%20replace(%22%5C%5C&type=code)

**Comment by Schamper** [comment]
Good catch. Will you create PRs yourself in the relevant places? Otherwise I'll make a start. I believe it's mostly an issue for the Unix filesystems, but will include the Windows ones too.

**Comment by JSCU-CNI** [comment]
Could you make a start?

**Comment by Schamper** [comment]
I believe these are it. Both `dissect.ffs` and `dissect.vmfs` already did this correctly, likely because I realized by then it wasn't actually correct, but never got around to fixing it in the other places :)

The changes in `dissect.ntfs` and `dissect.fat` are technically not required, but mostly made to be closer to the happy path, which may save a CPU cycle or two.

**Comment by JSCU-CNI** [comment]
Thanks for the quick fix. Can confirm this issue is resolved with the latest dev releases.
