### ISSUE TITLE
Specifying a directory as a target does not load target files that should be picked up by the RawLoader

### ISSUE THREAD

**Issue by Schamper** [fox-it/dissect.target#215]
Given the following directory structure:

```
targets/
├── IE11-Win81-VMWare-disk1.vmdk
├── MSEDGEWIN10_20220708124036.tar
├── SCHARDT.001
└── SCHARDT.raw
```

Performing `target-query targets/` will only load `MSEDGEWIN10_20220708124036.tar` because there's a specific loader for `.tar` files. All the other targets are skipped. These other targets will only load when doing `target-query targets/*`. This is not the expected behavior. All files in this directory should be loaded as targets when passing the directory path.

This is also documented incorrectly in the documentation, see https://github.com/fox-it/dissect-docs/pull/13.

**Comment by Zawadidone** [comment]
Thanks for fixing this issue!
