### ISSUE TITLE
Output OS version as record

### ISSUE THREAD

**Issue by Zawadidone** [fox-it/dissect.target#330]
I would like to change the current version functions of the operating systems to output the version as a record instead of text or add an additional function to output the version as a record.

How can this be implemented? 

https://github.com/fox-it/dissect.target/blob/29b54d7dbbe45cc76a9188470529e5e56cc94744/dissect/target/plugin.py#L348-L356

**Comment by JSCU-CNI** [comment]
You could use `target-info -r` to obtain the os version inside a record. For example:

```
$ target-info -r /path/to/target.img | rdump -F os_family,os_version

<target/info os_family='windows' os_version='Windows Server 2019 Standard Evaluation (NT 10.0) 1337.1337'>

**Comment by Zawadidone** [comment]
Can the info function and record (https://github.com/fox-it/dissect.target/blob/main/dissect/target/tools/info.py#L19) be moved to https://github.com/fox-it/dissect.target/tree/main/dissect/target/plugins/os? That way `target-query -f info [...]` and `target-info` can be used to obtain info about the target.

**Comment by Zawadidone** [comment]
@JSCU-CNI  I have added a suggestion in the PR https://github.com/fox-it/dissect.target/pull/336. The JSON output now also include target fields (`_source`, _classification`, etc). Should this be hidden from the output?


```json
# Previous output
{
    "hostname": "MSEDGEWIN10",
    "domain": null,
    "ips": [
        "192.168.150.128"
    ],
    "os_family": "windows",
    "os_version": "Windows 10 Enterprise Evaluation (NT 10.0) 17763.379",
    "architecture": "amd64-win64",
    "language": [
        "en_US"
    ],
    "timezone": "America/Los_Angeles",
    "install_date": "2019-03-19 12:59:35+00:00",
    "last_activity": null,
    "disks": [],
    "volumes": [],
    "children": []
}

# Record output (-j)
{
    "hostname": null,
    "domain": null,
    "last_activity": null,
    "install_date": "2019-03-19 12:59:35+00:00",
    "ips": [
        "192.168.150.128"
    ],
    "os_family": "windows",
    "os_version": "Windows 10 Enterprise Evaluation (NT 10.0) 17763.379",
    "architecture": "amd64-win64",
    "language": [
        "en_US"
    ],
    "timezone": "America/Los_Angeles",
    "disks": [],
    "volumes": [],
    "children": [],
    "_source": null,
    "_classification": null,
    "_generated": "2023-07-28 20:06:49.978362",
    "_version": 1
}
````

**Comment by Zawadidone** [comment]
Nevermind I forgot that the osinfo function can be used for this. https://github.com/fox-it/dissect.target/blob/051a2b5de54b1b931811610084465991fbfd8464/dissect/target/plugins/general/osinfo.py
