### ISSUE TITLE
PluginListPlugin output is nondeterministic

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/dissect.target#421]
Output of `target-query -l` seems to be nondeterministic across different host filesystems.

This is caused by the `find_py_files` function which effectively globs over files inside directories of the repository. The order of the returned files determines which `OSPlugin` is chosen for the `OS plugins` output of `target-query -l`.

This issue can be demonstrated fairly straightforward in docker. In the first example below we pull the dissect docker image as you normally would.

```bash
# First we pull the image in the default /var/lib/docker
docker run --rm -it ghcr.io/fox-it/dissect:latest bash

# Note the order of the windows and unix folders inside the container
$ ls -Uil /opt/3.9/lib/python3.9/site-packages/dissect/target/plugins/os
total 12
143880 -rw-r--r-- 1 root root    0 Sep 27 07:13 __init__.py
144033 drwxr-xr-x 8 root root 4096 Sep 27 07:13 windows
143881 drwxr-xr-x 2 root root 4096 Sep 27 07:13 __pycache__
143883 drwxr-xr-x 6 root root 4096 Sep 27 07:13 unix

# Note that we see 6 plugins below with WindowsPlugin documentation
$ target-query -l | head -n 10
Available plugins:
    OS plugins
      architecture - Returns a dict containing the architecture and bitness of the system (output: text)
      hostname - No documentation (output: text)
      ips - No documentation (output: text)
      os - No documentation (output: text)
      users - No documentation (output: records)
      version - Return a string representation of the Windows version of the target. (output: text)
...
```

We now change the docker daemon's `data-root` path and execute the same set of functions inside the container.
```bash
# We now pull to /tmp/test/foo
echo '{"data-root": "/tmp/test/foo"}' > /etc/docker/daemon.json
systemctl daemon-reload && systemctl restart docker
docker run --rm -it ghcr.io/fox-it/dissect:latest bash

# Note the order of the unix and windows folders inside the container
$ ls -Uil /opt/3.9/lib/python3.9/site-packages/dissect/target/plugins/os
total 12
443819 -rw-r--r-- 1 root root    0 Sep 27 07:13 __init__.py
443822 drwxr-xr-x 6 root root 4096 Sep 27 07:13 unix
443820 drwxr-xr-x 2 root root 4096 Sep 27 07:13 __pycache__
443972 drwxr-xr-x 8 root root 4096 Sep 27 07:13 windows

# Note that we see 7 plugins below with no documentation,
# which indicates that the UnixPlugin was selected.
$ target-query -l | head -n 10
Available plugins:
    OS plugins
      architecture - No documentation (output: text)
      domain - No documentation (output: text)
      hostname - No documentation (output: text)
      ips - No documentation (output: text)
      os - No documentation (output: text)
      users - No documentation (output: records)
      version - No documentation (output: text)
...
```

The same phenomenon can occur 'recursively' when the `unix` folder is chosen over the `windows` folder. In this instance, the `AndroidPlugin` or `IOSPlugin` could be chosen. This causes the `users` plugin to not be shown at all, since until recently these plugins were not exported at all.

In order to prevent this unexpected behaviour from happening in the future, we propose to document (add general pydoc strings) and show all functions defined in `OSPlugin` (`dissect/target/plugin.py`) instead of picking the last scanned `OSPlugin` in the `PluginListPlugin` (`categorized_plugins['']`).

**Comment by Schamper** [comment]
> In order to prevent this unexpected behaviour from happening in the future, we propose to document (add general pydoc strings) and show all functions defined in OSPlugin (dissect/target/plugin.py) instead of picking the last scanned OSPlugin in the PluginListPlugin (categorized_plugins['']).

Agreed, that seems like the proper solution.

**Comment by JSCU-CNI** [comment]
Thank you for the fix.
