### ISSUE TITLE
FortiOS extfs filesystem broken

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/dissect.target#468]
It seems that between dissect release 3.9 and 3.10 (or dissect.target 3.12 and 3.13) something changed which has broken FortiOS extfs filesystems.

We are currently working on improving the FortiOS support in dissect and stumbled upon this when rebasing to the current head of the dissect.target project.

```
$ pip freeze | grep dissect
dissect==3.9
dissect.target==3.12
$ target-shell /tmp/FortiGate-VM64.vmx
FortiGate-VM64.vmx /> volumes
<Volume name='part_00100000' size=268435456 fs=<ExtFilesystem>>
<Volume name='part_10100000' size=1810890752 fs=<ExtFilesystem>>
<Volume name='part_7c000000' size=67108864 fs=<FatFilesystem>>
<Volume name='part_00100000' size=32209147904 fs=<ExtFilesystem>>
```

The latest release does not detect the first extfs volume:
```
$ pip freeze | grep dissect
dissect==3.10
dissect.target==3.13
$ target-shell /tmp/FortiGate-VM64.vmx
FortiGate-VM64.vmx /> volumes
<Volume name='part_00100000' size=268435456 fs=None>
<Volume name='part_10100000' size=1810890752 fs=<ExtFilesystem>>
<Volume name='part_7c000000' size=67108864 fs=<FatFilesystem>>
<Volume name='part_00100000' size=32209147904 fs=<ExtFilesystem>>
```

This can be reproduced using the default FortiGate-VM images from https://support.fortinet.com/Download/VMImages.aspx. The example uses the latest 7.4.1 release for ESXi/VMware.

**Comment by Schamper** [comment]
https://github.com/fox-it/dissect.target/pull/456 might fix this. Some of the volume opening logic was changed recently.

**Comment by JSCU-CNI** [comment]
#456 fixes the described issue.

```
self.target.volumes
<VolumeCollection: [
  <Volume name='part_00100000' size=268435456 fs=<ExtFilesystem>>, 
  <Volume name='part_10100000' size=1810890752 fs=<ExtFilesystem>>, 
  <Volume name='part_7c000000' size=67108864 fs=<FatFilesystem>>, 
  <Volume name='part_00100000' size=32209147904 fs=<ExtFilesystem>>, 
  <Volume name='part_18063e5d600' size=221630011904 fs=None>, 
  <Volume name='part_1860e279a00' size=1000171537408 fs=None>, 
  <Volume name='part_00000000' size=0 fs=None>
]>

**Comment by Schamper** [comment]
#456 is merged, so I think this can be closed? I've snuck `SYSLINUX` into https://github.com/fox-it/dissect.volume/pull/24 so the weird looking volumes should disappear out of that list too.

**Comment by Politie-SOC** [comment]
#456 also fixes a (probably the same) bug that appeared when parsing Citrix Netscaler BSD images

**Comment by JSCU-CNI** [comment]
Thank you for the fix @Schamper. I can confirm volumes are correctly recognized with the patch from https://github.com/fox-it/dissect.volume/pull/24

```
$ target-shell /tmp/FortiGate-VM64.vmx
FortiGate-VM64.vmx /> volumes
<Volume name='part_00100000' size=268435456 fs=<ExtFilesystem>>
<Volume name='part_10100000' size=1810890752 fs=<ExtFilesystem>>
<Volume name='part_7c000000' size=67108864 fs=<FatFilesystem>>
<Volume name='part_00100000' size=32209147904 fs=<ExtFilesystem>>
