### ISSUE TITLE
evtx plugin doesn't parse all of the security log

### ISSUE THREAD

**Issue by hanfatzot** [fox-it/dissect.target#582]
When running the evtx plugin I noticed that it didn't parse all of the security log file and dumped only 1 record with EventID 4624. I extracted the file and read it using Event Viewer and saw that there were more than 1. Moreover, I tried using Evtx from dissect.eventlog.evtx and again I saw that there were more than 1.

**Comment by Schamper** [comment]
Hi @hanfatzot, was the problem resolved or did you accidentally close this?
