### ISSUE TITLE
Snap service key causes exception

### ISSUE THREAD

**Issue by Bopobopob** [fox-it/dissect.target#644]
I have an Ubuntu 20.04.6 image that has the service "snap.lxd.daemon.service" installed.
When running target.services(), it fails with exception.
``
flow.record.exceptions.RecordDescriptorError: Field 'Unit_X-Snappy' is an invalid or reserved field name.
``
I've managed to work around it by editing line 65 of target.plugins.os.unix.linux.services.py to
``
_key = f"{segment}_{key.replace("-","_")}"
``
The key in the record then comes out to,
``
Unit_X_Snappy='yes'
``
It runs successfully for my images at the moment, but I doubt it won't break something else down the line.

**Comment by Schamper** [comment]
Thanks for reporting! I've moved this to the dissect.target repo, as it looks like a bug in there.

@Miauwkeru I believe you rewrote the services plugin like this. I see no objections, do you?

**Comment by Schamper** [comment]
@Bopobopob let us know if you'd like to create your own PR or if you'd like us to fix this instead!

**Comment by Bopobopob** [comment]
I'll try to send one your way today

**Comment by Schamper** [comment]
Closed via https://github.com/fox-it/dissect.target/pull/647
