### ISSUE TITLE
Unexpected exception handing

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/dissect.target#684]
Currently most `dissect.\*` filesystem projects have their own `exceptions.py` defintions for e.g. `FileNotFoundError` classes. These classes are often sub-classed by a local `Error` class, which in turn is sub-classed by Python's `Exception`.  [1]

This all works fine, **except** when exceptions are returned from a filesystem project to a 'parent' project such as `dissect.target`, which has it's own exception definitions which cannot be compared with exceptions from other child projects.

This leads to circumstances where `FileNotFoundError != FileNotFoundError` in `dissect.target` - which causes unintentional bugs and unexpected behaviour.

To demonstrate, we recently encountered a bug in `dissect.target` `record_modifier.py`'s `modify_record` function. When the Windows MFT contains a reference to a file which no longer exists or does not exist yet on disk, and `target-query -f mft --hash` is called, dissect would break as `FileNotFoundError` is not handled here. [2]

```python
try:
    _record = modifier_function(field_name, resolved_path)
except FilesystemError:
    pass
```

One would assume adding `except (FilesystemError, FileNotFoundError):` would fix this. This however does not fix the issue, since we receive `dissect.ntfs.exceptions.FileNotFoundError` and try to compare it against Python's `FileNotFoundError` (or `dissect.target.exceptions.FileNotFoundError` when importing that explicitly). This comparison fails as these exceptions have different underlying types. [3] We could add a generic `Exception` handler but that would likely be too broad.

Specifically adding NTFS's `FileNotFoundError` is likely also unwanted, since the `modify_record` function is not NTFS or MFT specific. 

We have identified some possible solutions for this problem:

- a generic `dissect.exceptions` project which defines generic exceptions universally for all dissect projects
- preventing filesystem projects to return their own exception classes and use generic Python exceptions instead
- sub-classing filesystem project exceptions with Python's built-in exceptions  
  
  We're interested to learn the reasoning behind separate `exceptions.py` classes for each project, perhaps there's something fundamental or dissect specific we are misunderstanding here.
  
  [1] https://github.com/fox-it/dissect.ntfs/blob/main/dissect/ntfs/exceptions.py
  [2] https://github.com/fox-it/dissect.target/blob/main/dissect/target/helpers/record_modifier.py#L81
  [3] https://docs.python.org/3/library/exceptions.html

**Comment by cecinestpasunepipe** [comment]
We would like to retain the current project-specific exception classes, as their removal would necessitate all projects to rely upon either a dedicated exceptions project (1) or dissect.target. Employing generic Python exceptions (2) or extending them would cause significant disruption to our extant code base.

We maintain that exceptions related to particular subprojects should be explicitly caught and managed; they are indicative of distinct error categories. For example, an `NTFS FileNotFound` error carries a different implication than a `SquashFS FileNotFound` error, each likely stemming from different underlying issues. Consequently, handling these exceptions typically requires custom logic tailored to each situation to arrive at an effective resolution.

Nonetheless, if your code is agnostic to the specific causes behind a `FileNotFound` error, catching the general Error exception may suffice. In such contexts, utilizing the generic Error exception is an appropriate strategy, as it does not overly generalize the error handling process.

**Comment by Schamper** [comment]
Thanks for the follow up. I have to say I don't agree with the idea of introducing a `dissect.exceptions` for numerous reasons. If you want we can have a follow-up discussion on the exact why's, just let me know.

However, after some collaborative brainstorming I think we found a nice middle ground. We could change all relevant filesystem errors to _also_ subclass from their respective Python counterparts. This way, you only have to catch the "native Python" exception variant. This of course only works for errors which have a native Python counterpart:

```
In [31]: class MyError(Exception):
    ...:     pass
    ...:

In [32]: class MyNotADirectoryError(MyError, NotADirectoryError):
    ...:     pass
    ...:

In [33]: try:
    ...:     raise MyNotADirectoryError()
    ...: except NotADirectoryError:
    ...:     print("happy times")
    ...:
happy times
```

I can't think of any downside to this approach, other than the fact that it will require a lot of changes to properly propagate throughout the codebase.

I'm interested to know what your thoughts are on this.
