### ISSUE TITLE
Bug in plocate plugin

### ISSUE THREAD

**Issue by jadevries** [fox-it/dissect.target#696]
Using the plocate file parser class outside of the Dissect context I noticed a bug: (almost) every 32nd path gets appended to the previous path. 
While testing with target-query I also could reproduce this behaviour on Debian, Ubuntu and Fedora.

I tested and reproduced this on:
Fedora 39: python 3.12.0 (plocate 1.1.17)
Fedora 40: python 3.12.2 & python 3.9.19 (plocate 1.1.22)
Ubuntu 11.04: python 3.10.12 (plocate 1.1.15)
Debian 11: python 3.9.2 (plocate 1.1.8-2)

plugin function used: https://github.com/fox-it/dissect.target/blob/b1bcb0d89d3b24a9ad7e8150d63ddd6dd30a82a2/dissect/target/plugins/os/unix/locate/plocate.py#L138C21-L138C26

**Comment by Horofic** [comment]
@JSCU-CNI Have you noticed any similar behaviour on your side? This behaviour does not seem to occur in the related test-cases.
