### ISSUE TITLE
Separate lookup of directory entries in `DirectoryFilesystem.get` into another method.

### ISSUE THREAD

**Issue by Schamper** [fox-it/dissect.target#708]
Currently all the logic is in `get()` but there are some cases where you may want to subtly tweak how filesystem entries are mapped. The logic should be separated out into another method(s) so that subclasses may customize the behaviour.

**Comment by Zawadidone** [comment]
How should this be implemented? I expect that file entries are already mapped when the filesystem is initialized.

**Comment by Schamper** [comment]
The `DirectoryFilesystem` doesn't do any mapping, so any customization in lookup can be done dynamically:
https://github.com/fox-it/dissect.target/blob/94cd431d0c33a3f940670f510683486b9538498d/dissect/target/filesystems/dir.py#L30-L55

**Comment by Zawadidone** [comment]
Is it not better that `DirectoryFilesystem` maps the paths into the virtual file system, by using `map_file_entry`? 

This way there is no situation where the paths are 'stored' in the `DirectoryFilesystem` in URL encoded format. Otherwise the lookup functionality should be added to all functions of `DirectoryFilesystemEntry`, because these functions don't use the function `get()`.

**Comment by Schamper** [comment]
The `DirectoryFilesystemEntry.get()` method calls `self.fs.get()`, I'm not sure what you mean? If you put it in `DirectoryFilesystem.get()`, it should work universally.

My idea was to maybe have some kind of `_resolve_path(path)` method in the `DirectoryFilesystem` class. The base class can then contain these lines:

https://github.com/fox-it/dissect.target/blob/94cd431d0c33a3f940670f510683486b9538498d/dissect/target/filesystems/dir.py#L36-L49

The `VelociraptorDirectoryFilesystem` class can than subclass `DirectoryFilesystem`, implement its own `_resolve_path(path)` that basically does:

```python
return super()._resolve_path(unquote(path))
```

That way you also get case insensitiveness for free.

**Comment by Zawadidone** [comment]
Okay I will work on that.

**Comment by Zawadidone** [comment]
Implemented in [`84a9cc0` (#700)](https://github.com/fox-it/dissect.target/pull/700/commits/84a9cc0b6c2c179174cd4aedaf063cf13a362d5e)
