### ISSUE TITLE
Feature Request: Teamviewer Plugin for Linux OS and macOS

### ISSUE THREAD

**Issue by h0ckeyst1ck** [fox-it/dissect.target#740]
Hi there!
I am working my way through the python API and I noticed in the source code that the TeamViewer plugin is only looking for windows paths at the moment. It was an explanation why it didn't work on my test case. I would be very happy to see linux paths added to the plugin as it already is for anydesk. 
Many thanks in advance!

**Comment by Schamper** [comment]
Thanks for bringing this up! I've created an accompanying ticket for acquire as well: https://github.com/fox-it/acquire/issues/178
