### ISSUE TITLE
Get DHCP lease ips from /var/lib On Linux based operating systems

### ISSUE THREAD

**Issue by AlonHaviv1** [fox-it/dissect.target#960]
On various Linux based network managers, the DHCP leases are stored on various files.

For example, in NetworkManager, The DHCP lease ip are stored in `/var/lib/NetworkManager/*.lease`.
In dhclient, these are stored in `/var/lib/dhcp/dhclient.leases`.

Those are sample of a better solution to finding Target Ip, instead of parsing syslog, which in some cases could be a more resource intensive task.

**Comment by Horofic** [comment]
Hey @AlonHaviv1 thank you for opening this issue! This is indeed the the case. At the moment, we are carefully moving away from the current implementation in [network_managers.py](https://github.com/fox-it/dissect.target/blob/main/dissect/target/plugins/os/unix/linux/network_managers.py) that has this behaviour. 

I think this would be a good addition in the new Linux network manager implementation found [here](https://github.com/fox-it/dissect.target/blob/main/dissect/target/plugins/os/unix/linux/network.py). Although you might still want to parse some lines in the `syslog` or `messages` as a fallback when the paths you named fail to reveal a DHCP lease.

Lastly, is this something you are willing to pick up in the form of a pull-request?
